{% set name = "azure-storage-blob" %}
{% set version = "12.18.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8ced0deee3367fa3d4f3d1a03cd9edadf4440c0a371f503d623fa6c807554ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - azure-core <2.0.0,>=1.28.0
    - cryptography >=2.1.4
    - isodate >=0.6.1
    - typing-extensions >=4.3.0

test:
  imports:
    - azure.storage.blob
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/azure-storage-blob/
  summary: Microsoft Azure Blob Storage Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - xhochy
