{% set name = "azure-storage-blob" %}
{% set version = "12.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eaaaa1507c8c363d6e1d1342bd549938fdf1adec9b1ada8658c8f5bf3aea844e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - typing_extensions >=4.6.0
    - python >={{ python_min }}
    - azure-core >=1.30.0
    - cryptography >=2.1.4
    - isodate >=0.6.1
    - typing-extensions >=4.6.0

test:
  imports:
    - azure.storage.blob
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/azure-storage-blob/
  summary: Microsoft Azure Blob Storage Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - xhochy
