{% set name = "azure-storage-blob" %}
{% set version = "1.5.0" %}
{% set sha256 = "f187a878e7a191f4e098159904f72b4146cf70e1aabaf6484ab4ba72fc6f252c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - azure-common >=1.1.5
    - azure-storage-common >=1.4.0,<1.5.0

test:
  imports:
    - azure
    - azure.storage
    - azure.storage.blob

about:
  home: https://github.com/Azure/azure-storage-python
  license: Apache-2.0
  license_family: Apache
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: 'Microsoft Azure Storage Blob Client Library for Python'

extra:
  recipe-maintainers:
    - xhochy
